### ISSUE TITLE
Python 3 raises a NameError because of file builtin

### ISSUE THREAD

**Issue by alexprengere** [erocarrera/pydot#107]
Hello, I am using `pydot2==1.0.33` with Python 3.4. It seems that the `pydot.Dot.write_png` does not work with Python 3 because of the `file` builtin, removed in Python 3, causing a `NameError`.

**Comment by sbenthall** [comment]
I am also having trouble with pydot and Python 3.
I am trying to 

`conda install pydot`

when I have conda in python3.

Are patches for Python3 compatibility welcome?

**Comment by log0** [comment]
TL;DR: pip3 install pydot3 / pip install pydot3

I found that this repro doesn't work in Python 3.x and made a quick fix to be Python 3.x compatible and made it accessible via pip install.

**Comment by alexprengere** [comment]
Ok thanks I will test your repository. Out of curiosity, why not fixing this repository instead of creating another package? Indeed it seems no commits have been done since 2012, pull requests and issues do not seem to get much attention.

**Comment by alexprengere** [comment]
I switched from `pydot2` to `pydot3` and I got this error:
```python
>>> import pydot
>>> pydot.Dot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Dot'
```

I dit not dig into the code, but it is probably some trivial `__init__.py`  missing import bug. I will open a proper issue in your repository, since this does not seem like the appropriate place to report this.

**Comment by IARI** [comment]
I cannot use pydot3, because https://github.com/log0/pydot3/issues/3

I cannot use this version because `pip3 install pydot` doesn't work either.

I am totally confused wrt. the existing versions now.

**Comment by johnyf** [comment]
The latest release of `pydot == 1.1.0` does *not* support Python 3. This restriction is declared by the classifier "Programming Language :: Python :: 2.7" at: https://pypi.python.org/pypi/pydot/1.1.0

The next release, `pydot == 1.2.0` (marked as [milestone 1.2.0](https://github.com/erocarrera/pydot/milestones/1.2.0) above) will support Python 3.

Other PyPI entries related to `pydot` are forks (including `pydot3`), and some of them have been updated to Python 3. What is currently in progress is (me) reviewing the changes in the forks with most extensive and consistent work, that appear here as branches:

https://github.com/erocarrera/pydot/tree/nlhelper_master
https://github.com/erocarrera/pydot/tree/pydotplus_master
https://github.com/erocarrera/pydot/tree/ng_master

and applying changes from them, together with other changes. The Python 2 version has been fixed (e.g., wrt compatibility with `pyparsing`), and the next major change will be support for Python 3, which will be reflected in the trove classifiers used on PyPI.

**Comment by IARI** [comment]
@johnyf thank you for your exhaustive answer, I have a few questions:
- When do you plan to release 1.2.0 ?
- is there something that you need help with
- what would in your opinion be the best approach to get a working dot parser with python 3.4 right now

**Comment by johnyf** [comment]
- I plan to release 1.2.0 by June 30.
- I think that the best approach to get a working parser in Python 3.4 for now is to install either from the branch `nlhelper_master` here, or the fork's repository, or `pip install pydotplus`.
- Thanks for offering to help, I will come back to this with specific action items.

**Comment by johnyf** [comment]
@IARI, most changes to Python 3 have been applied on branch `dev`. The remaining ones are:

1. updating string I/O
2. running tests under Python 3 and on Travis CI.

It would be helpful if you could review that branch, and confirm that it works for you, after No.1 is addressed. Running the tests locally would also be helpful. Thanks.

**Comment by johnyf** [comment]
6081f6d96b2d45dad0d77e7e4d6a9a36f863031c should address the OP.
