### ISSUE TITLE
pydot cant find graphviz2.38 on windows 7 from MSI installer

### ISSUE THREAD

**Issue by isaacgerg** [erocarrera/pydot#109]
Path it should check for is `C:\Program Files (x86)\Graphviz2.38\`

but it only looks in `C:\Program FIles\Graphviz\bin`

**Comment by johnyf** [comment]
It seems that `pydot` looks at [`$PROGRAMFILES\ATT\GraphViz\bin`](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L540) and [`C:\Program Files\att\Graphviz\bin`](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L545), not the reported `C:\Program FIles\Graphviz\bin`.

Is that a typo in the OP?

**Comment by johnyf** [comment]
Thanks for noting a suggested path. [It appears](C:\Program Files (x86)\Graphviz(VersionNumber)) to be the default installation location of GraphViz on Windows. However, that path is system-specific (x86) and specific to GraphViz version. So, hardcoding it within `pydot` wouldn't be a stable improvement.

The OS vendor can decide to change the location however they like from OS version to version. Likewise, GraphViz can change its default installation location as it likes, and the user can also override that at will, perhaps appending a `2.38` or trimming it.

The existing [`find_graphviz`](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L408) function is an assembly of search heuristics that are fragile to changes over time. For *nix systems, the `$PATH` is a respected and preserved mechanism, so looking there, and at [a few standard FHS locations](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L555) is relatively robust on Linux and OS X.

**Comment by johnyf** [comment]
The suggested change is to search in directories of the form `C:\Program Files\Graphviz*` and `C:\Program Files (x86)\Graphviz*`. However, this would lead to a search through directories.

Even worse, there is no way to choose among multiple installed versions of GraphViz. So, an implicit arbitrary choice would have to be made, and any warning can go unnoticed. It is better to explicitly ([PEP 20](https://www.python.org/dev/peps/pep-0020/)) make the user add GraphViz to the `$PATH`, as they may have to do on other systems too (Linux, OS X).

In this way, the user intentionally chooses among possibly multiple GraphViz versions installed on the system, instead of making an arbitrary choice among directories detected on the system.

**Comment by johnyf** [comment]
Same with #65. An example file search for a GraphViz directory has been [proposed here](https://github.com/erocarrera/pydot/issues/65#issuecomment-92396972).

**Comment by johnyf** [comment]
A different solution is proposed in #102 and will be preferred, because it is explicit, robust, and agnostic of OS and GraphViz version.

**Comment by johnyf** [comment]
Running binaries at fixed arbitrary paths is a security and privacy vulnerability. This behavior was removed by ed32d4e91b20c06e636717696dc410e75c9ffbe9. Only the `$PATH` is searched (in future changes, this may be replaced by a call to `subprocess`).

For posterity, the installation instructions of GraphViz explicitly support the [above](https://github.com/erocarrera/pydot/issues/109#issuecomment-219192993) decision that "It is better to explicitly make the user add GraphViz to the `$PATH`". Specifically for Windows, they write [in bold and large size font](http://www.graphviz.org/Download_windows.php):

"Note: As of version 2.31, ... If you wish to use the command-line interface to Graphviz or are using some other program that calls a Graphviz program, you will need to set the PATH variable yourself."
