### ISSUE TITLE
InvocationException: GraphViz's executables not found

### ISSUE THREAD

**Issue by TaeheeJeong** [erocarrera/pydot#116]
Please help the following error.

```
  File "c:\anaconda\lib\site-packages\pydotplus\graphviz.py", line 1797, in <lambda>
    lambda f=frmt, prog=self.prog: self.create(format=f, prog=prog)

  File "c:\anaconda\lib\site-packages\pydotplus\graphviz.py", line 1960, in create
    self.progs[prog] = os.path.normpath(self.progs[prog][1:-1])

InvocationException: GraphViz's executables not found
```

The error message comes out when `"Image(graph.create_png())"`
I already installed Graphviz2.38 and added path and install `pydotplus`.
My operating system is window 7.

**Comment by johnyf** [comment]
This seems to not be a `pydot` issue, but rather graphviz executables not found in the `$PATH`.
Please check your path manually, and make sure that Anaconda doesn't mess with it. On Unix systems, [`which`](https://en.wikipedia.org/wiki/Which_%28Unix%29), [`hash`](https://en.wikipedia.org/wiki/Hash_%28Unix%29), and [`type`](https://en.wikipedia.org/wiki/Type_%28Unix%29) are the relevant commands that typically resolve path-related problems.

The relevant line is [`graphviz` L1960](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L1960).

Regarding how graphviz executables are searched, for windows [this is tried first](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L430), [that later](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L527) (the `"win32"` [identifies windows regardless of bitness](http://stackoverflow.com/a/2145582/1959808). [In between](https://github.com/erocarrera/pydot/blob/ebfd155d60a6000fedb2169c0d963ed5acfcf0e1/pydot.py#L517), the `$PATH` is searched.

Also, https://github.com/carlos-jenkins/pydotplus is a fork of `pydot`, and the relevant line there is [`graphviz` L1959](https://github.com/carlos-jenkins/pydotplus/blob/c0219c8be6bd7a24143fbe66c0dd9022b7fa49e4/lib/pydotplus/graphviz.py#L1959). So, if there is a relevant change applied here, then you will need to install `pydot`. Besides, the code `self.progs[prog] = os.path.normpath(self.progs[prog][1:-1])` above doesn't match the `pydotplus` code, neither the `pydot` code at those lines.

**Comment by johnyf** [comment]
See also #91 and #109.

**Comment by johnyf** [comment]
The answer [above](https://github.com/erocarrera/pydot/issues/116#issuecomment-219188413) is now outdated, because the code has changed. For the changes, please see the closing comment here: https://github.com/erocarrera/pydot/issues/91#issuecomment-229639358.
