### ISSUE TITLE
pydot2 -  Couldn't import dot_parser, loading of dot files will not be possible

### ISSUE THREAD

**Issue by mrkafk** [erocarrera/pydot#117]
% pip freeze | egrep 'pypars|pydot'
    pydot2==1.0.33
    pyparsing==2.1.0

    % python -c 'import pydot'
    Couldn't import dot_parser, loading of dot files will not be possible.

    % python -V
    Python 2.7.10

**Comment by johnyf** [comment]
Fixed by 042e78ee7edbefef78508a8ac8b7567a180309c0.
