### ISSUE TITLE
Is pydot maintained?

### ISSUE THREAD

**Issue by alexprengere** [erocarrera/pydot#119]
Hello,
I am a pydot user. On PyPI, both [pydot](https://pypi.python.org/pypi/pydot) and [pydot2](https://pypi.python.org/pypi/pydot2/1.0.32) documentation have links pointed to http://code.google.com/p/pydot/, which is actually a redirection to this repository, suggesting that here is the place to address issues/pull requests.

The last commits on this repository were made 4 years ago, and it does not seem that issues or pull requests are being processed at all. I am not suggesting I could maintain pydot, I just want to know who is able to upload pydot packages PyPI, and if there is another version being maintained somewhere.

**Comment by jgillis** [comment]
Perhaps this project is more up to date: https://github.com/log0/pydot3/

**Comment by johnyf** [comment]
As of now, `pydot` has a new maintainer (myself) that can upload releases on PyPI. There are a number of forks (not very actively maintained), but not another "main" repository. The forks contain updates that fix several maintenance issues, so I plan to start reviewing and merging/editing these changes, to make a new release.

See also https://github.com/nlhepler/pydot/issues/12#issuecomment-217775011
