### ISSUE TITLE
Error in pydot-1.2.2 

### ISSUE THREAD

**Issue by essank** [erocarrera/pydot#124]
I am trying to run some Tensorflow in my machine.
This is the code:

```python
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
test_idx = [0, 50, 100]

#training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

#testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print test_target
print clf.predict(test_data)

import pydot
from sklearn.externals.six import StringIO
dot_data = StringIO()
tree.export_graphviz(clf, out_file=dot_data,
                         feature_names=iris.feature_names,
                         class_names=iris.target_names,
                         filled=True, rounded=True,
                         special_characters=True)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")
``` 

The output is that:
```
/Users/essank/anaconda/lib/python2.7/site-packages/pydot.py:33: UserWarning: Couldn't import dot_parser, loading of dot files will not be possible.
  "Couldn't import dot_parser, "
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    graph = pydot.graph_from_dot_data(dot_data.getvalue())
  File "/Users/essank/anaconda/lib/python2.7/site-packages/pydot.py", line 235, in graph_from_dot_data
    return dot_parser.parse_dot_data(s)
NameError: global name 'dot_parser' is not defined
```
How I can fix it?

**Comment by johnyf** [comment]
It appears that `dot_parser` failed to import [here](https://github.com/erocarrera/pydot/blob/b835fb1c532f73d8ae0ea4d9d18052489cdb8f93/pydot.py#L33), which printed the `UserWarning`. Given that the tests pass on Travis CI, this is likely to be caused by [absence of `pyparsing`](https://github.com/erocarrera/pydot/blob/b835fb1c532f73d8ae0ea4d9d18052489cdb8f93/dot_parser.py#L14), or an old version.

Could you try in `ipython` to run `from pydot import dot_parser` and see what the error is? You may also want to check what version of `pyparsing` is installed, e.g., `pip show pyparsing`.

**Comment by essank** [comment]
@johnyf The error is:
```Unreadable Notebook: /Users/essank/Desktop/test.ipynb NotJSONError("Notebook does not appear to be JSON: u'import numpy as np\\nfrom sklearn.datas...",)```

and pyparsing version is ```2.1.5```

**Comment by johnyf** [comment]
Thanks for the details. This is the latest version of `pyparsing`. This appears to not be a `pydot` error, rather an error with `ipython` notebooks. These appear to be relevant:

https://github.com/iit-cs579/main/issues/39
http://stackoverflow.com/questions/32103772/unreadable-notebook-notjsonerrornotebook-does-not-appear-to-be-json-u-n
http://stackoverflow.com/questions/22156147/ipython-notebooks-unreadable
http://stackoverflow.com/questions/32711302/ipython-notebook-does-not-appear-to-be-json
