### ISSUE TITLE
Can't find find_graphviz()

### ISSUE THREAD

**Issue by willgdjones** [erocarrera/pydot#126]
Where has `find_graphviz()` gone? It's needed for for the documentation examples in Keras.

Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pydot
>>> pydot.find_graphviz()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'find_graphviz'

**Comment by willgdjones** [comment]
https://github.com/fchollet/keras/issues/3216

**Comment by johnyf** [comment]
The function `pydot.find_graphviz` was an internal function that should have been hidden as `_find_graphviz`. It was removed in bc639e76b214b1795ebd6263680ee55d9d4fca9f, and replaced by the standard library's (superior) functionality available in `subprocess`. It was made obsolete in ed32d4e91b20c06e636717696dc410e75c9ffbe9, among other commits.

The original version of `find_graphviz` is a security liability, besides other problems. Please see [this comment](https://github.com/erocarrera/pydot/commit/812e3c40dac1e0225391481073c64da5bafba93e#commitcomment-18222580) for further information on this.

Thanks for pointing to the `keras` package issue. As I remarked in https://github.com/fchollet/keras/issues/3216, there is no reason to call `pydot.find_graphviz` explicitly. Essentially the same error message will be shown to the user if they try to plot, but the desired GraphViz executable is not found in the `$PATH`.

So, just removing that call to `find_graphviz` should solve the problem.

**Comment by willgdjones** [comment]
Yep fixed. Thanks!

**Comment by johnyf** [comment]
Great!

**Comment by AziziShekoofeh** [comment]
As you mentioned and I checked the earlier posts too (https://github.com/fchollet/keras/issues/3216), I have tried pydot_ng and different package version of pydot. I can import pydot.find_graphviz, either using pydot_ng or pydot in my own codes but it is generating this error or the same each time.


apparantely it's trying to call:

**Comment by johnyf** [comment]
Thanks for reporting this issue. This appears to be a bug in `keras`: https://github.com/fchollet/keras/blob/ff1f79603296bffc312076afa0589d229145924c/keras/utils/visualize_util.py#L13.

Firstly, that the line `if not pydot.find_graphviz()` is reached means that either `pydot_ng` or `pydot` was imported. That an `ImportError` is raised on the next line means that either `pydot_ng` was succesfully imported, or an older version of `pydot`. With the current `pydot`, an `AttributeError` would have been raised instead by the line `if not ...`.

The `ImportError` message on this line: https://github.com/fchollet/keras/blob/ff1f79603296bffc312076afa0589d229145924c/keras/utils/visualize_util.py#L14 is inaccurate. By the reasoning above, some `pydot` variant was successfully imported. What cannot be found is GraphViz.

So, you need to install [GraphViz](http://graphviz.org/) *and* ensure that `dot` is in your `$PATH`. I would recommend opening a pull request to `keras` that:

1. updates those lines to use `pydot == 1.2.3`, following this comment: https://github.com/erocarrera/pydot/commit/812e3c40dac1e0225391481073c64da5bafba93e#commitcomment-18236709, which was implemented in `theano`
2. removes the dependence on `pydot_ng`
3. possibly adds `pydot == 1.2.3` to the `install_requires` of `keras` (https://github.com/fchollet/keras/blob/ff1f79603296bffc312076afa0589d229145924c/setup.py#L13).

Also, [`pydot_ng`](https://github.com/pydot/pydot-ng/tree/master/pydot_ng) is unmaintained (last commit in 2015), in favor of upstream (here). The comment "pydot-ng is a fork of pydot that is better maintained." is outdated, it was introduced with https://github.com/fchollet/keras/commit/e5d3abdf09d8c281ca8817b6292a044673ba3007, so before maintenance of `pydot` resumed.

**Comment by enduringstack** [comment]
try pydotplus

**Comment by johnyf** [comment]
`pydotplus` is an unmaintained fork of `pydot`, and bug fixes and some other changes from it have been merged upstream.

**Comment by jecs89** [comment]
I found a manual solution:
sudo apt-get install graphviz

graph.write('test.dot')
dot -Tps test.dot -o outfile.ps

You can the files here: https://github.com/jecs89/LearningEveryDay/tree/master/GP

**Comment by johnyf** [comment]
[GraphViz](http://graphviz.org/) is a dependency of `pydot` and needs to be installed separately. Using [`apt`](https://en.wikipedia.org/wiki/APT_(Debian)) to install GraphViz is one possible approach. Installing `pydot` is a separate item from installing GraphViz.

**Comment by jecs89** [comment]
I see but I am not using pydot, I am using pydotplus.

**Comment by johnyf** [comment]
`pydotplus` is an unmaintained fork of `pydot`.
