### ISSUE TITLE
Crashes when attempting to generate output

### ISSUE THREAD

**Issue by chintal** [erocarrera/pydot#128]
pydot crashes when attempting to write output. The following is the relevant portion of the traceback.

```python
File ".../python2.7/site-packages/pydot.py", line 1768, in write
    s = self.create(prog, format)
File ".../python2.7/site-packages/pydot.py", line 1891, in create
    err=stderr_data))
KeyError: 'cmdline'
```

This seems to correspond to the following code, which exists also in the [current git version](https://github.com/erocarrera/pydot/blob/master/pydot.py#L1885) :

```python
if p.returncode != 0:
            print(
                ('{cmdline} return code: {c}\n\n'
                 'stdout, stderr:\n {out}\n\n').format(
                     c=p.returncode,
                     out=stdout_data,
                     err=stderr_data))
```

**Comment by johnyf** [comment]
Thanks for reporting this. It had been fixed in #125, and is available on branch `dev` as of f28296d436f208b0f6a2961de4e1fd5f88160691.
