### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by redraven984** [erocarrera/pydot#129]
I dont this is the right forum to post this question, but I am really at a loss and I dont know where to post.

I have a graph created in rdflib in python and parsed to a *.rdf file. I would like to load it using pydot and then plot it using Graphviz. Can someone please help me as to the syntax to load a graph using pydot and then to plot it out in literally any format in Graphviz.

**Comment by johnyf** [comment]
This issue tracker is for `pydot`, which can parse `.dot` files, but not `.rdf` files (unless they are dot files too -- I do not know what this format is). The `rdflib` project appears to be located [here](https://github.com/RDFLib/rdflib). An example of loading and writing to some image format can be found in the [tests](https://github.com/erocarrera/pydot/blob/69dce474f6fbcaa6055586611453e43f3f20230d/test/pydot_unittest.py#L160). Also, in [this](http://stackoverflow.com/a/5316307/1959808) discussion, and [here](https://pythonhaven.wordpress.com/2009/12/09/generating_graphs_with_pydot/).
