### ISSUE TITLE
Release python 2.6 fix to `pydot.py`

### ISSUE THREAD

**Issue by yalwan-scee** [erocarrera/pydot#131]
Would you be willing to make a new release of pydot which contains the fix 95a32c3dda4d7f0962d51bddbd103ca988affd0d?

**Comment by johnyf** [comment]
Yes, thank you for speaking up. I was planning to release this earlier (hence the gap betwen v1.2.2 and milestone 1.3.0). I have shifted 1.3.0 and created a milestone for 1.2.3.

**Comment by yalwan-scee** [comment]
Am I correct in understanding that the milestone deadline means you intend to provide this tomorrow? Will it also appear in pypi?

Thank you very much for your swift response.

**Comment by johnyf** [comment]
Yes, this will be a release of branch `dev` more or less as it is now, and I will upload it to PyPI.

**Comment by yalwan-scee** [comment]
Is there an ETA for when this would be available?

**Comment by johnyf** [comment]
I will try to release it within the next 24h.

**Comment by leycec** [comment]
@johnyf **Pydot is currently [critically broken](https://github.com/networkx/networkx/pull/2272#issuecomment-251863106) for _all_ Python 2.x versions.**

I have a working fix, but it will probably take several hours to submit the pull request. Would you mind holding off on 1.2.3 until then? Resolving the breakage is fairly critical to downstream projects (e.g., NetworkX).

**Comment by johnyf** [comment]
@leycec thanks, that change appears reasonable. No worries, in case you cannot open a pull request now, I can commit it, with you as `--author`.

**Comment by leycec** [comment]
Sweet! You're awesome. I _think_ I got this, though. I'm about five minutes away from pushing the submit button.

One thing that _would_ be excellent on your part, however, would be a new **unit test** exercising this issue. I'd hate for this to regress at some point. Cheers! :crown:

**Comment by leycec** [comment]
Pull request #135 is off and away. _Yay!_

**Comment by johnyf** [comment]
`pydot == 1.2.3` has been released on PyPI. Tag: https://github.com/erocarrera/pydot/tree/v1.2.3.

**Comment by yalwan-scee** [comment]
I'd like to thank you both for your contributions and swift work. It is highly appreciated!
