### ISSUE TITLE
pydot.Dot.create() raises Non-human-readable `KeyError` on Failing Command

### ISSUE THREAD

**Issue by leycec** [erocarrera/pydot#133]
The `pydot.Dot.create()` method raises a non-human-readable `KeyError` exception when the executed command returns non-zero exit status. As a common example, when called from NetworkX via the `networkx.nx_pydot.pydot_layout()` function, the stacktrace resembles:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/leycec/py/networkx/networkx/drawing/tests/test_pydot.py", line 86, in testUndirected
    nx.nx_pydot.pydot_layout(G, prog='neato')
  File "/home/leycec/py/networkx/networkx/drawing/nx_pydot.py", line 285, in pydot_layout
    D=P.create(prog=prog, format='raw')
  File "/usr/lib64/python3.4/site-packages/pydot.py", line 1891, in create
    err=stderr_data))
KeyError: 'cmdline'
```

"Why, _why_!?", you are probably muttering. I shall tell you why. The `{cmdline}` format key referenced on line 1887 of `pydot.py` is undefined. To trivially resolve this, consider passing a `cmdline=cmdline,` keyword argument to the `format()` call on line 1888.

Long live the One True Pydot! :small_airplane:

**Comment by johnyf** [comment]
Thanks for reporting this. It had been fixed in #125, #128, and will be released in v1.2.3.

**Comment by leycec** [comment]
_Whoops._ I only checked the `master` branch for changes, neglecting the mainline development isolated at the GitFlow-style `dev` branch.

I can see I'm in good hands here. :grin:

**Comment by johnyf** [comment]
The branch `dev` is informal, and I also delete and recreate it (nearly equivalent to force-pushing). Therefore, it is not a stable branch. The reference branch is `master`. What can be done instead is to add a note to the README about development practices followed (i.e., point at branch `dev`).
