### ISSUE TITLE
how can i convert networkx graph to pydot graph ?

### ISSUE THREAD

**Issue by gaopengpian** [erocarrera/pydot#146]
The networkx can convert graph to pydotplus graph in default. How can i convert to pydot, not pydotplus ?

**Comment by johnyf** [comment]
`networkx == 1.10` used `pydot`. `networkx == 1.11` switched to `pydotplus`. The current `master` branch of `networkx` reverted to `pydot` by merging https://github.com/networkx/networkx/pull/2272.
