### ISSUE TITLE
Why does the get_node() function return a list ?

### ISSUE THREAD

**Issue by gaopengpian** [erocarrera/pydot#147]
I notice that get_node() return a Node list() from 'self.obj_dict['nodes'][name]'. 
When has the name include more than one Nodes ?

**Comment by johnyf** [comment]
The method [`pydot.Graph.get_node`](https://github.com/erocarrera/pydot/blob/35a8d858bd9da0b37268fe9b317fe4895387e75f/pydot.py#L1153) describes the different cases for its return values in its docstring. You can read the docstring either in the source code, or with:

- `help(pydot.Graph.get_node)`
- `print(pydot.Graph.get_node.__doc__)`
- `pydot.Graph.get_node` (within `ipython`, not within a normal `python` shell)

**Comment by gaopengpian** [comment]
Thanks for you replay. I have read the source code, I still don't know when will the length of the return list be more than 1 ? Did the 'self.obj_dict['nodes'][name]' be always point to a single on node?  Can you make an example ?
