### ISSUE TITLE
Cannot install with IronPython 2.7.7 and pip

### ISSUE THREAD

**Issue by danielschenk** [erocarrera/pydot#148]
When I try to install using pip with IronPython 2.7.7, I get the following error:
![2017-01-24_10h47_16](https://cloud.githubusercontent.com/assets/9695838/22270854/e76948dc-e291-11e6-8929-e0c85a8f3825.png)

When I use IronPython 2.7.5 instead, it works:
![2017-01-24_13h38_33](https://cloud.githubusercontent.com/assets/9695838/22270896/1a33efd8-e292-11e6-84f2-bee75cdfb786.png)

**Comment by johnyf** [comment]
The OP reports the error

```
...six.py", line 692, in exec_
AttributeError: 'module' object has no attribute '_getframe'
```

`pydot` doesn't call the function `_getframe` anywhere.
The `six` module [does call](https://github.com/benjaminp/six/blob/16cab6c7a558f03ed4a95d667caa89c01255d64c/six.py#L698) the function [`sys._getframe`](http://stackoverflow.com/a/1140231/1959808). From the [documentation](https://docs.python.org/2/library/sys.html#sys._getframe):

"CPython implementation detail: This function should be used for internal and specialized purposes only. It is not guaranteed to exist in all implementations of Python."

Based on https://github.com/kennethreitz/requests/issues/553#issuecomment-5197044, IronPython may not support `sys._getframe`. See also https://github.com/kennethreitz/requests/issues/553#issuecomment-5197575, and [this answer](http://stackoverflow.com/a/6999692/1959808).

You could consider opening an issue for the package `six`.
