### ISSUE TITLE
Couldn't import dot_parser on Python 3.6.4

### ISSUE THREAD

**Issue by huyvohcmc** [erocarrera/pydot#166]
```
>>> import pydot
Couldn't import dot_parser, loading of dot files will not be possible.
>>> 
```
```

pip3 freeze | egrep 'pydot|pyparsing'
pydot2==1.0.33
pyparsing==2.2.0
```

I'm using Python 3.6.4 on a Mac:

<img width="1222" alt="screen shot 2018-01-08 at 7 32 25 pm" src="https://user-images.githubusercontent.com/17645203/34671061-8554112c-f4ab-11e7-9a3f-bb5fa9dea159.png">

**Comment by johnyf** [comment]
`pydot2` is installed, not `pydot`. To install `pydot`:

```
pip uninstall pydot2
pip install pydot
```

With `pydot >= 1.2.5` installed via `pip`, I wouldn't expect any issues with `dot_parser` (because a suitable version of `pyparsing` would be installed too.
