### ISSUE TITLE
how to get dot graph depth

### ISSUE THREAD

**Issue by Forever22** [erocarrera/pydot#167]
how to get dot graph depth, not the max dot graph depth. It is meaningful to analyze th class called relation, thanks a lot

**Comment by johnyf** [comment]
How is "graph depth" defined? There is no class called "Relation" in `pydot`.

**Comment by Forever22** [comment]
for example,  in CLASS_GRAPH,
a->b, the depth is 2.
a->b, b->c, c->d, the depth is 4.
a->b, b->c, c->d, a->x, b->y, the depth is 4.

**Comment by johnyf** [comment]
There is a class `Graph` in `pydot` (but no identifier `CLASS_GRAPH`).

[`networkx`](https://github.com/networkx/networkx/) is a package suitable for computing properties of graphs (it includes implementations of several algorithms). This sketch of depth seems to refer to acyclic graphs. In general, the *diameter* of a graph is probably what the OP alludes to.

`networkx` includes [computation of a graph's diameter](https://github.com/networkx/networkx/blob/0bbacf8125083753248a7b334aff5762bb13dda9/networkx/algorithms/distance_measures.py#L11).

`pydot` is a package for only interfacing to GraphViz for layout purposes (plotting). In other words, `pydot` is not a library of graph algorithms, unlike `networkx`. Usually one works with graphs using `networkx`, and at the time of plotting converts to `pydot` using `networkx.drawing.nx_pydot.to_pydot`.

**Comment by Forever22** [comment]
OK, thanks a lot
