### ISSUE TITLE
using the argument `obj_dict` when creating new edge

### ISSUE THREAD

**Issue by vnelis** [erocarrera/pydot#168]
Hi,

I want to redirect an edge. That is, I want to change its destination node.
Since there is no function set_destination, I do as follows:

My graph is called `G` and contained an edge `E` that is connecting node `A` to node `B`

```python
new_edge = pydot.Edge(A, B, obj_dict=E.obj_dict['attributes'])
print(new_edge)
graph.add_edge(new_edge)
graph.del_edge(A, B)
```

This raises an Error when printing `new_edge` (`KeyError: 'points'`).
The reason is simple. When looking at the code of `__init__` in the class `Edge`:

```python
        self.obj_dict = dict()
        if isinstance(src, Node):
            src = src.get_name()
        if isinstance(dst, Node):
            dst = dst.get_name()
        points = (quote_if_necessary(src), quote_if_necessary(dst))
        self.obj_dict['points'] = points
        if obj_dict is None:
            # Copy the attributes
        else:
            self.obj_dict = obj_dict
```

Since I provide the parameter `obj_dict`, I end up in the "else" case at the end and the last line overwrites the "points" key that has been added to `obj_dict` at the beginning of the function. 

Best,
Vincent

(Thank you for this library!!)

**Comment by johnyf** [comment]
The keyword argument `obj_dict` needs to be a `dict` with contents appropriate for an `object_dict`, i.e., the keys `'points', 'attributes', 'type', 'parent_graph`, ...`. Passing the value of one of those keys, namely `E.obj_dict['attributes']` as `obj_dict` is expected to raise such an error.

Passing `obj_dict=E.obj_dict`, or `obj_dict=dict(E.obj_dict)` satisfies this requirement, and doesn't raise any error.

Sidenote: It appears that `new_edge` and `E` have the same source and target node (assuming a directed graph), so the target node would be the same.

Also, the relevant lines are:

https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/pydot.py#L658-L676

which differ in formatting from the OP (possibly using another `pydot` version).
