### ISSUE TITLE
Exception on calling graphViz with a directory including space

### ISSUE THREAD

**Issue by sasrazor** [erocarrera/pydot#172]
I installed graphViz according to instructions and added graphViz's path to the system $PATH. But I found
when graphViz was installed in a directory including space, such as the default directory "c:\program files\graphviz\" on Windows 7, an exception occured with error information "'dot.exe' not found in path". 
But I can run dot.exe under Window command line successfully. 

 I  tried changing the directory to "c:\program\graphviz\"  and run pydot again, there is no error. 

So I think this is a bug of pydot, please check it.

**Comment by johnyf** [comment]
I successfully invoked GraphViz via `pydot` on Windows, with executables (`dot.exe` etc) installed at `C:\Program Files (x86)\Graphviz2.38\bin`. I modified the path as follows from a command prompt:

```
set "PATH=%PATH%;C:\Program Files (x86)\Graphviz2.38\bin\"
```

which can be confirmed with `echo %PATH%`. After this change of the path variable, the following succeeds:

```python
import pydot
pydot.Dot().create()
```

returning a string in PostScript (starting with `%!PS-Adobe-3.0`), which is the default format:

https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/pydot.py#L1762

**Comment by sasrazor** [comment]
Thanks johnyf! I followed your steps and it really worked well. 

But it is said on Stackoverflow that, for security reasons, Windows just save the PATH temporarily when you set PATH from a command prompt. Once you close the CMD terminal, it fails. Therefore, if you want to save PATH variable permanently, please run CMD as an administrator. I'm not sure about that since I haven't checked yet. 

As an alternative, users can also manually set the PATH variable by following steps: Computer->Properties->Advanced Properties->Environmental Variables->Edit Path variable. But I just made the mistake here. As is known to all, we usually place double-quote marks around the path containing spaces in windows batch scripts to avoid unknown errors. Empirically, I appended "C:\Program Files (x86)\Graphviz2.38\bin\" with double-quote marks to the PATH string. As what I mentioned at the very begining, it throws exception. After I delete the quote marks, pydot calls GraphViz successfully.

**Comment by peternowee** [comment]
For those who are seeing this problem with Graphviz installed through conda/Anaconda, see: https://github.com/conda-forge/graphviz-feedstock/issues/43.
