### ISSUE TITLE
Empty Output File

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#3]
Hi Ero,

I am running pydot on Mac OS X 10.5.1 and am experiencing the empty output
file problem as described in
http://code.google.com/p/pydot/wiki/EmptyOutputFiles.

I added the path to graphviz to my path and the executables are being
found.  This was verified via a debugger by stepping through the pydot
source code.

The source of my problem is the statement "data = stdout.read()" in
Dot.create() is not returning anything and thus "data" has no value.

I examined the temporary file referenced by stdout and verified that it
contains data.

I am running with the following versioned software:

  * pydot - 0.9.10
  * graphviz - 2.14
  * python - 2.5

Keith

Original issue reported on code.google.com by `kscho...@cisco.com` on 18 Dec 2007 at 9:34

**Comment by johnyf** [comment]
As noted above, this issue had been fixed. The current code is somewhat different (with `write_pdf` etc.), and is expected that in this case it should throw an error due to `subprocess.Popen.returncode != 0` inside `pydot.Dot.create`.
