### ISSUE TITLE
Invalid command line generated when extra parameters specified

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#68]
What steps will reproduce the problem?
1. Generate any graph structure
2. Call the write function with a list as the parameter, using more than one 
value in the list. For example :
`graph.write_svg(somefile, prog=['twopi', 'overlap=scale'])`

Expected : The graph is generated using the extra settings specified
Actual : The library raises an error saying that the command line was invalid 
(with the example above:

```
"InvocationException: Program terminated with status: 
2. stderr follows: Error: twopi: can't open overlap=scale")
```

Pydot-1.0.28-py2.7, on windows 7 x64

I think the bogus line is line 1985:
`cmdline = [self.progs[prog], '-T'+format, tmp_name] + args`

The error is that the `args` list is appended at the end of the command list, 
while they should be placed between the `-T` and input elements (the rule being 
that the input files must be placed at the end of the command)

Original issue reported on code.google.com by `xrogerma...@gmail.com` on 8 Mar 2012 at 6:21

**Comment by johnyf** [comment]
The OP is correct: the file name `tmp_name` should be the last argument. This was fixed by 667e60e03cc5edcc3fa1bb4a99d957012bb0a9cd. So, calling: `g.write_svg('hehe.svg', prog=['twopi', '-Goverlap=scale'])` works. Notice the prefix `-G` that signifies a graph attribute.

**Comment by johnyf** [comment]
`pydot.Dot.write` uses `self.prog` as set by the method `Dot.set_prog`, [here](https://github.com/erocarrera/pydot/blob/b835fb1c532f73d8ae0ea4d9d18052489cdb8f93/pydot.py#L1761).

**Comment by johnyf** [comment]
The above [comment](https://github.com/erocarrera/pydot/issues/68#issuecomment-92396999) is also correct, i.e., the error in the OP is due to not prepending `-G`, and not due to the order of arguments. In any case, the order of arguments now matches the documentation of graphviz.
