### ISSUE TITLE
Prints to stdout if cannot load dot_parser

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#69]
If `dot_parser` cannot be loaded in `pydot`, a message is printed to `stdout`. I 
believe it's incorrect. A message should be printed to `stderr` (as in the 
following patch), or not printed at all.

```
*** pydot.py.orig	2012-03-20 13:48:01.009730200 +0400
--- pydot.py	2012-03-20 13:48:27.784195800 +0400
***************
*** 23,28 ****
--- 23,29 ----
  __license__ = 'MIT'
  
  import os
+ import sys
  import re
  import subprocess
  import tempfile
***************
*** 30,36 ****
  try:
      import dot_parser
  except Exception, e:
!     print "Couldn't import dot_parser, loading of dot files will not be 
possible."  
  
--- 31,37 ----
  try:
      import dot_parser
  except Exception, e:
!     print >> sys.stderr, "Couldn't import dot_parser, loading of dot files 
will not be possible."
```

Original issue reported on code.google.com by `cmr.P...@gmail.com` on 20 Mar 2012 at 10:05

**Comment by johnyf** [comment]
Fixed by #97, because [`warnings.warn` messages are normally written to `sys.stderr`](https://docs.python.org/2/library/warnings.html#warnings-warning-control). This is a good argument for using `warnings.warn`, instead of `print`.
