### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#76]
The Python 3-compatible branch mentioned on the project home page is over a 
year old, so apparently it's not kept up-to-date with `pydot` development. The 
latest tag is for version 1.0.15, whereas 1.0.28 is the current version of `pydot`.

Python 3 is becoming more and more mainstream, especially for new projects. It 
would be very nice to be able to use `pydot` in Python 3.x projects too.

Original issue reported on code.google.com by `syb...@stuvel.eu` on 5 Nov 2012 at 1:43

**Comment by andreabedini** [comment]
bump, @nlhepler

**Comment by nlhepler** [comment]
@andreabedini, I think Google has decided I'm upstream...?! Cool, but strange. Seeing as erocarrera owns the original, perhaps we should just actually create a legitimate fork?

**Comment by andreabedini** [comment]
There's [a bunch](https://github.com/search?q=pydot&type=Repositories) of people who have made copies of the Google code repo. The good news is that the git hashes should be exactly the same for everyone so merges between the new repos are possible.

I came across this trying to make [theano](http://www.deeplearning.net/software/theano) work with pydot. The version of pydot from pypi didn't work well but your fork did.

happy to help if you and @erocarrera decide to merge.

**Comment by sandrotosi** [comment]
@erocarrera now is marked correctly as upsteam.

Now, another problem with the py3k patch in Debian:

```
>>> import pydot
>>> a=pydot.Dot()
>>> a.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pydot.py", line 2003, in create
    stdout_output = ''.join(stdout_output)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by NucleaPeon** [comment]
I am getting errors regarding python3 compatibility.

    pydot/setup.py", line 5
        except ImportError, excp:

and when I fix that error:

    pydot/pydot.py", line 32
        except Exception, e:

`print` commands are also not python3 compatible. 

Is there going to be a python3 compatible fork coming out of this project?

**Comment by sandrotosi** [comment]
FTR: I updated the patch (and so even the package) to https://anonscm.debian.org/cgit/python-modules/packages/pydot.git/tree/debian/patches/0002-support-python3.patch (which is basically https://github.com/nlhepler/pydot/ as of today)

**Comment by johnyf** [comment]
As of cb0dfe193166da8bc8f2279821b82dc1a930ebff, `pydot` runs in both python 2 and 3.
There were some minor API changes along the way, mainly to draw a clear distinction between unicode (strings) and bytes, and keep bytes at bay at the program boundaries, as is the recommended paradigm after the introduction of python 3. Explicit is better than implicit, and bytes should not be confused with unicode.
