### ISSUE TITLE
Setting default graph/node/edge attrs in an existing graph has no effect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#80]
What steps will reproduce the problem?
1. `g = pydot.graph_from_dot_data(""" digraph G { 1 -> 2; } """)`
2. `g.set_node_defaults(style="filled", fillcolor="yellow")`
3. `g.write_png("simple.yellow.png")`

What is the expected output? What do you see instead?
Should see yellow nodes, but nodes are still white.

What version of the product are you using? On what operating system?
Pydot 1.0.28, Python 2.7.3

Please provide any additional information below.

Default attributes are added to the BOTTOM of the DOT spec, after existing 
nodes and edges, so they don't take effect. They should be inserted at the TOP 
of the spec to take effect everywhere.

The attached file demonstrates the problem and the solution.

```python
import pydot

g = pydot.graph_from_dot_data("digraph G {1 -> 2;}")
print("Simple DOT:\n{0}".format(g.to_string()))
print("Nodes: {0}, edges: {1}".format(len(g.get_nodes()), len(g.get_edges())))
g.write_png("simple.png")

g.set_node_defaults(style="filled", fillcolor="yellow")
print("DOT with yellow fill (wrong):\n{0}".format(g.to_string()))
g.write_png("simple.yellow.png")

g = pydot.graph_from_dot_data("""
digraph G {
    node [style=filled, fillcolor=yellow];
    1 -> 2;
}
""")
print("DOT with yellow fill (good):\n{0}".format(g.to_string()))
g.write_png("simple.good.png")
```

Original issue reported on code.google.com by `zvi.ta...@gmail.com` on 1 Mar 2013 at 9:46

Attachments:
- [pydot_bug.py](https://storage.googleapis.com/google-code-attachments/pydot/issue-80/comment-0/pydot_bug.py)

**Comment by johnyf** [comment]
From the [description of the DOT language](https://www.graphviz.org/doc/info/lang.html):

> If a default attribute is defined using a **node**, **edge**, or **graph** statement, or by an attribute assignment not attached to a node or edge, any object of the appropriate type defined afterwards will inherit this attribute value. This holds until the default attribute is set to a new value, from which point the new value is used. Objects defined before a default attribute is set will have an empty string value attached to the attribute once the default attribute definition is made.

So there is no unique default value of node attributes. The default can change throughout the DOT source, and it applies to only nodes defined later. For example:

```python
p = pydot.Dot()
p.set_node_defaults(style="filled", fillcolor="blue")
p.add_node(pydot.Node('a'))
p.add_edge(pydot.Edge('a', 'b'))
p.set_node_defaults(style="filled", fillcolor="yellow")
p.add_node(pydot.Node('c'))
print(str(p))
p.write_png('foo.png')
```

The `Dot` class records the order in which elements of a graph are defined. This order determines which nodes are affected when setting a default style.

Internally, setting a default style for nodes is represented by creating a node named `node`:

https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/pydot.py#L930-L932

and the element order is recorded within the method `add_node`:

https://github.com/erocarrera/pydot/blob/d6ac9e9244d1a882103422ac2b35ceef96f5dfe3/pydot.py#L1093

The issue has been addressed by documenting the behavior of the method `set_node_defaults` in its docstring.
