### ISSUE TITLE
update to pyparsing >= 2.0.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#81]
```
What steps will reproduce the problem?
1. Try to install pydot from pip on OS X.

What is the expected output? What do you see instead?

That it installs correctly.

What version of the product are you using? On what operating system?

pydot 1.0.28 on OS X 10.8.2

Please provide any additional information below.

Probably just need an versioned depend on pyparsing, something like:

Index: setup.py
===================================================================
--- setup.py	(revision 29)
+++ setup.py	(working copy)
@@ -31,5 +31,5 @@
         'Topic :: Software Development :: Libraries :: Python Modules'],
     long_description = "\n".join(pydot.__doc__.split('\n')),
     py_modules = ['pydot', 'dot_parser'],
-    install_requires = ['pyparsing', 'setuptools'],
+    install_requires = ['pyparsing<2.0.0', 'setuptools'],
     data_files = [('.', ['LICENSE', 'README'])] )
```

Original issue reported on code.google.com by `WJWwood` on 4 Mar 2013 at 1:01

**Comment by eraoul** [comment]
Any progress here? 

This fixes it for me:
pip install pydot2

> import dot_parser

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/dot_parser.py", line 23, in <module>
    from pyparsing import ( nestedExpr, Literal, CaselessLiteral, Word, Upcase, OneOrMore, ZeroOrMore,
ImportError: cannot import name _noncomma
>>>

**Comment by vdboor** [comment]
It seems `pip install pydot2` is a nice workaround.

**Comment by sandrotosi** [comment]
FTR: I updated the patch (and so even the package) to https://anonscm.debian.org/cgit/python-modules/packages/pydot.git/tree/debian/patches/0002-support-python3.patch (which is basically https://github.com/nlhepler/pydot/ as of today)

**Comment by johnyf** [comment]
6dff94b3f1dbcf68e5a83ce17a36b098c06d7c6b fixes this issue, by applying the changes suggested above, and present in `nlhelper/pydot` and other forks, (to not `from pyparsing import _noncomma`), and [also the unused `pyparsing.Upcase`](https://github.com/erocarrera/pydot/commit/09abd83c5b50b851fac8cb87205dabc35caf1220), which has been removed too from `pyparsing >= 2.0.1`.

Note that these changes [make `pydot >= 1.1.0` compatible with `pyparsing >= 1.5.7`](https://github.com/erocarrera/pydot/commit/e26af21426fcf15955f7b11b348b14dc6bd5178c).
