### ISSUE TITLE
Multiple test failures (Ubuntu 13.04, graphviz 2.26.3-14ubuntu1)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#84]
What steps will reproduce the problem?
1. cd test && python pydot_unittest.py

What is the expected output? What do you see instead?
Expected: all tests pass
Actual: several tests fail (details below)

What version of the product are you using? On what operating system?
- svn r29 from http://pydot.googlecode.com/svn/trunk/
- Ubuntu 13.04
- Python 2.7.4 (OS package)
- pyparsing 1.5.7+dfsg1-0ubuntu2 (OS package)
- graphviz 2.26.3-14ubuntu1 (OS package)

Please provide any additional information below.

The following test case failed:

```python
TestGraphAPI.test_attribute_with_implicit_value
TestGraphAPI.test_create_simple_graph_with_node
TestGraphAPI.test_graph_pickling
TestGraphAPI.test_graphviz_regression_tests
TestGraphAPI.test_my_regression_tests
TestGraphAPI.test_quoting
TestGraphAPI.test_subgraphs
TestGraphAPI.test_unicode_ids
```

I'll attach a log of the complete run.

Original issue reported on code.google.com by `gerg.w...@gmail.com` on 20 Sep 2013 at 5:50

Attachments:
* [test-failures.log](https://storage.googleapis.com/google-code-attachments/pydot/issue-84/comment-0/test-failures.log)

**Comment by johnyf** [comment]
All tests pass on Travis CI as of b9579fb.
