### ISSUE TITLE
Include tests into release tarball

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#90]
Hello,
the tarball does not contain unittest as available at 
http://pydot.googlecode.com/svn/trunk/test/ which is rather unfortunate since 
they are an important verification tool (in particular for Linux Distribution 
as Debian, for which I package pydot).

Please consider including those tests into the released tarballs.

Regards,
Sandro

Original issue reported on code.google.com by `sandro.tosi` on 21 Mar 2014 at 9:05

**Comment by johnyf** [comment]
Addressed by ae80697e61e9e3b265175676bb78db6396542616.
