### ISSUE TITLE
add option to pass explicitly path to GraphViz executable (useful in Windows 7)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#91]
I am running Windows 7 64-bit. I installed graphviz-2.36.msi from 
http://www.graphviz.org/Download_windows.php but I install most programs to 
c:\app rather than c:\Program Files, and I get this message (see below). One 
problem is that there is no SOFTWARE\ATT registry key anymore. (perhaps related 
to https://code.google.com/p/pydot/issues/detail?id=65)

I think the bigger problem is that this discovery mechanism is a cat-and-mouse 
game with whatever the graphviz folks do.

===> Could you please add a function so that end-users can just set the 
graphviz path manually through whatever mechanism they see fit?

For now I'm just monkeypatching the pydot module:

```python
def force_find_graphviz(graphviz_root):
   binpath = os.path.join(graphviz_root, 'bin')
   programs = 'dot twopi neato circo fdp sfdp'
   def helper():
     for prg in programs.split():
       if os.path.exists(os.path.join(binpath, prg)):
         yield ((prg, os.path.join(binpath, prg)))
       elif os.path.exists(os.path.join(binpath, prg+'.exe')):
         yield ((prg, os.path.join(binpath, prg+'.exe')))
   progdict = dict(helper())
   return lambda: progdict
   
pydot.find_graphviz = force_find_graphviz('c:/app/util/graphviz/2.36')



C:\tmp\blockdiag>python
Python 2.7.5 |Anaconda 1.9.1 (64-bit)| (default, May 31 2013, 10:45:37) [MSC v.1
500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydot
Couldn't import dot_parser, loading of dot files will not be possible.
>>> graph = pydot.Dot(graph_type='graph')
>>> graph.write_png('test.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pydot.py", line 1602, in
<lambda>
    lambda path, f=frmt, prog=self.prog : self.write(path, format=f, prog=prog))

  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pydot.py", line 1696, in
write
    dot_fd.write(self.create(prog, format))
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pydot.py", line 1724, in
create
    self.progs = find_graphviz()
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pydot.py", line 409, in f
ind_graphviz
    "SOFTWARE\ATT\Graphviz", 0, win32con.KEY_QUERY_VALUE )
pywintypes.error: (2, 'RegOpenKeyEx', 'The system cannot find the file specified
.')
>>>
```

Original issue reported on code.google.com by `jmsa...@gmail.com` on 28 Mar 2014 at 7:30

**Comment by KentChun33333** [comment]
This saves my day! Thanks : )

**Comment by RunshengSong** [comment]
Saved my day too!!

**Comment by Ben-Gillman** [comment]
I'm running Windows 10 with Python 2.7 on the Anaconda Prompt.

I have replaced the "def find_graphviz():" function with your code above.

But when I run Import Pydot, I receive the following error:
  File "C:\Users\...\AppData\Local\Continuum\Anaconda2\lib\site-packages\pydot.py", line 432
    return None
              ^
IndentationError: unindent does not match any outer indentation level

This is how I have the function currently defined in pydot.py:

###########################################################
def find_graphviz():
    if os.sys.platform == 'win32':


        if os.environ.has_key('PROGRAMFILES'):
            #Change to your path
            path =  "C:\Program Files\Graphviz2.30\\bin"


        else:

            #Just in case, try the default...
            path = r"C:\Program Files\Graphviz2.30\bin"

        progs = __find_executables(path)

        if progs is not None :

            #print "Used default install location"

            return progs


        return None
#############################################3
Please let me know how to alleviate this error.

Thank you,
Ben

**Comment by johnyf** [comment]
The OP suggests that the user be able to pass the path of GraphViz. The standard approach to this problem is to add GraphViz to the path. Hardcoding its path is not a solution #109. Nonetheless, adding an argument `graphviz_path` to `write` and its [`write_*`](https://github.com/erocarrera/pydot/blob/5e903e15b27a57bf300560cbea90d772a092a9b3/pydot.py#L1808) siblings is flexible, and can accommodate also selecting a GraphViz executable from within Python code, in any OS, without modifying the `$PATH`.

Thanks for the suggestion, this should also provide an alternative for #109, #102, #65 for users that prefer to not change the path.

**Comment by johnyf** [comment]
Addressed by f3abbd537ed8adfeb2c5562f6c62403094111aa8, which allows passing the path to the desired GraphViz executable as the `prog` argument of method `pydot.Dot.write_*` (for example, `write_pdf('filename.pdf', prog='C:\\some\\path\\dot.exe')`. It remains to test this on Windows.

The mentioned change also implements properly `$PATH` searching, by using `os.environ['PATH']` and the `env` argument of `subprocess`.

Relevant discussion and issues:
http://stackoverflow.com/a/5659249/1959808
http://bugs.python.org/issue8557

**Comment by jecs89** [comment]
I found a manual solution:
sudo apt-get install graphviz

graph.write('test.dot')
dot -Tps test.dot -o outfile.ps

You can the files here: https://github.com/jecs89/LearningEveryDay/tree/master/GP

**Comment by johnyf** [comment]
Please see https://github.com/erocarrera/pydot/issues/126#issuecomment-347301268
