### ISSUE TITLE
pydot 1.0.28 on pypi?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#96]
```
Hello there,

I've noticed that with pip 1.5, pip install pydot gives the old (and for my 
purposes) pydot 1.0.2.

Would it be possible for the current pydot (1.0.28?) to be uploaded to PyPI?  
If I understand correctly, the issue is that whilst it is mentioned in the 
index, the actual tarball is externally hosted on code.google.com; and also 
does not come with a hash.  Perhaps uploading directly to pypi would simplify 
installation for users?

Currently, for example, all of my pip requirements.txt files require these lines

--allow-external pydot
--allow-unverified pydot

Moreover the need for these means that users with pip 1.4 (default on MacOS X 
10.9.4, for example) will not be able to install my packages without first 
upgrading pip.

Many thanks!
```

Original issue reported on code.google.com by `eric....@gmail.com` on 18 Sep 2014 at 1:35

**Comment by grooverdan** [comment]
seems to be completed:

$ pip install pydot
Downloading/unpacking pydot
  Downloading pydot-1.0.28.tar.gz

**Comment by sbidoul** [comment]
This issue is still present. pip install pydot installs version 1.0.2. It would be great to have at least the source distribution on pypi.

```
(venv2)sbi$ ~/tmp$ pip list
pip (8.0.2)
setuptools (18.4)

(venv2)sbi$ ~/tmp$ pip install pydot
Collecting pydot
  Downloading pydot-1.0.2.tar.gz
Collecting pyparsing (from pydot)
  Downloading pyparsing-2.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv2/lib/python2.7/site-packages (from pydot)
Installing collected packages: pyparsing, pydot
  Running setup.py install for pydot ... done
Successfully installed pydot-1.0.2 pyparsing-2.1.0

(venv2)sbi$ ~/tmp$ pip list
pip (8.0.2)
pydot (1.0.2)
pyparsing (2.1.0)
setuptools (18.4)
```

**Comment by sbidoul** [comment]
Moreover --allow-external and --allow-unverified are deprecated in pip and have no effect.

**Comment by sebastienbeau** [comment]
I am also impacted

**Comment by geota** [comment]
My company is impacted as well.

**Comment by johnyf** [comment]
I will upload the existing tarball for v1.0.28 to PyPI. Next will be a v1.0.29 that will differ only in that the `install_requires` will pin `pyparsing`. This will allow installing from PyPI, with all the existing assumptions about dependencies, so that packages that compensate for them (e.g., by installing an older `pyparsing`) will still work. Later releases will update to the current `pyparsing`.

**Comment by johnyf** [comment]
The source tarball for `pydot == 1.0.28` has been uploaded to PyPI:

https://pypi.python.org/packages/fe/4f/d019aa298dd5dca4ebf5f14d74173eee83d643fcdabbb7e8145843154efa/pydot-1.0.28.tar.gz#md5=c0a7a027176a62c412fd0f54951af692

and can be installed with:

`pip install pydot`

or, more specifically:

`pip install pydot==1.0.28`

This tarball is exactly the same that has been available from GoogleCode at: http://pydot.googlecode.com/files/pydot-1.0.28.tar.gz and is still listed as "Download URL" on PyPI (no need for `pip` to follow that URL, which anyway it doesn't any more).

Note that this release does not pin `pyparsing` in `install_requires` to any particular version. `pydot == 1.0.28` is incompatible with the latest `pyparsing`, but that concerns only parsing `.dot`, which is less frequent a use case, compared to writing `.dot`. In any case, the `pyparsing` dependency will be pinned and updated in #117, #97, #81.
